# Markdownlint configuration
config:
  # MD013: Line length
  MD013:
    line_length: 100
    code_blocks: false
    tables: false
  
  # MD033: Allow inline HTML (useful for documentation)
  MD033: false
  
  # MD041: First line in file should be a top level heading
  MD041: false

# Ignore patterns
ignores:
  - node_modules
  - .pixi
  - build
  - dist
  - "*.egg-info"
